#!/bin/bash
myip=$(wget --timeout=30 http://ipinfo.io/ip -qO -)
myipV6=`dig TXT +short o-o.myaddr.l.google.com @ns1.google.com | sed 's/"//g' |grep -E -v "([0-9]{1,3}[\.]){3}[0-9]{1,3}"`
HOSTNAME=`nslookup $myip |grep -v "server can't find" |grep -v "Authoritative" | awk '{print $4}'`
wget --timeout=30 http://api.db-ip.com/v2/free/$myip -qO - |grep -v '{' |grep -v '}' |sed 's/"//g'

if [ -z "$myipV6" ]
then
      echo "\$var is empty" >> /dev/null
else
      echo "    IPV6: $myipV6"
fi

if [ -z "$HOSTNAME" ]
then
      echo "\$var is empty" >> /dev/null
else
      echo "    Hostname: $HOSTNAME" 
fi



