#!/bin/bash
myip=$(wget --timeout=30 http://ipinfo.io/ip -qO -)
curl -s http://api.db-ip.com/v2/free/$myip |grep -v '{' |grep -v '}' |sed 's/"//g'
nslookup $myip |grep -v "server can't find" |grep -v "Authoritative"
